# Generated by Django 5.2.1 on 2025-05-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('Tricycle', 'Tricycle'), ('Motorcycle', 'Motorcycle'), ('Multicab', 'Multicab'), ('Bus', 'Bus')], max_length=50)),
                ('availability', models.CharField(max_length=100)),
                ('travel_area', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
