# Generated by Django 5.2.1 on 2025-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_ids/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
