# Generated by Django 5.2.1 on 2025-05-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverprofile_license_id_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_id_image',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='profile_picture',
        ),
    ]
