# Generated by Django 5.2.1 on 2025-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driverprofile_license_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
