# Generated by Django 5.2.1 on 2025-05-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverprofile_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='plate_number',
        ),
    ]
